raw_data_path: "../data/processed/gefcom_wind_all_zones.csv"

split:
  train_cut: "2013-09-01"
  val_cut: "2013-11-01"

features:
  lags:[1,2,3,6,12,24]
  rolling_windows:[6, 24]

processed_output: "./data/processed/gefcom_wind_all_zones_features.csv"
target: "TARGETVAR"