data:
  path: "../data/featured"
  target: "target"

train:
  model: "lightgbm"
  test_size: 0.2
  random_state: 42
  learning_rate: 0.1
  n_estimators: 100

#other options
model:
  name: "lightgbm"
  params:
    learning_rate: 0.05
    n_estimators:: 300
    max_depth: -1

output_dir: "./output"